name: Daily Refresh API Cache

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  build-refresh-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: gh-pages

    - name: Fetch user repositories API data
      uses: JamesIves/fetch-api-data-action@v2.4.1
      with:
        endpoint: https://api.github.com/users/vellfr00/repos?type=owner&sort=updated&direction=desc
        configuration: '{ "method": "GET", "headers": { "Authorization": "Bearer ${{ secrets.GET_USER_PUBLIC_REPOSITORIES_GITHUB_API_TOKEN }}" } }'
        debug: true
  
    - name: Copy user repositories API response
      run: cp fetch-api-data-action/data.json api__cache/github/vellfr00/cached__getUserPublicRepositories.json

    - name: Remove fetch-api-data-action directory
      run: rm -rf fetch-api-data-action

    - name: List complete build directory
      run: ls -R build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: .
        clean: false
        commit-message: 'Daily refresh of API cache'